### ISSUE TITLE
Why the reported result of DDGCN in this paper is different with your former paper Orders Are Unwanted: Dynamic Deep Graph Convolutional Network for Personality Detection.

### ISSUE THREAD

**Issue by djp0823** [TaoYang225/PsyCoT#1]
DDGCN result on Kaggle dataset 71.35(71.59) in Paper Orders Are Unwanted: Dynamic Deep Graph Convolutional Network for Personality Detection.

the TrigNet result is also lower than original paper.
![屏幕截图 2024-01-07 181833](https://github.com/TaoYang225/PsyCoT/assets/155883001/6a290255-0819-401c-9e18-a1eb7ce2870f)

**Comment by TaoYang225** [comment]
hi, limited by API resources, we randomly selected 200 samples from the test set to evaluate PsyCoT and baselines

**Comment by djp0823** [comment]
I'm not asking the result of psyCoT, but trained model DDGCN.

**Comment by TaoYang225** [comment]
The baselines, including DDGCN and TrigNet, are evaluated on the same randomly selected test samples for fair comparison with PsyCoT.
